### ISSUE TITLE
How to display the actual reader name instead of numbers

### ISSUE THREAD

**Issue by FeitianSmartcardReader** [LudovicRousseau/CCID#102]
@LudovicRousseau Our customer using R502 Dual interface reader on macOS/Linux, and they found the reader name shows below:
![image](https://user-images.githubusercontent.com/9547938/197922537-dd7ab11f-1e39-4c91-8ee4-61a3ae694ebc.png)

is that passible to have the reader name? 
![image](https://user-images.githubusercontent.com/9547938/197922604-39e5e492-98b0-4acf-8be2-3d4f44b91068.png)

**Comment by LudovicRousseau** [comment]
The reader name is not selected by the CCID driver but by the layer above.

- On GNU/Linux it is pcsc-lite (and the PC/SC name contains the interface name). See [What is in a PC/SC reader name?](https://ludovicrousseau.blogspot.com/2010/05/what-is-in-pcsc-reader-name.html)
- On macOS it is Crypto Token Kit (CTK)

CTK does not support multi interfaces CCID readers. The CCID driver has to fake a multislot reader instead.

You should ask Apple to:

1. support composite (multi interfaces) CCID readers
2. add the interface name in the reader name

**Comment by LudovicRousseau** [comment]
Only Apple can fix your problem.

**Comment by FeitianSmartcardReader** [comment]
Noted with thanks
