### ISSUE TITLE
Question on Bluetooth Smart Card Readers

### ISSUE THREAD

**Issue by agorgl** [LudovicRousseau/CCID#108]
I see that there are some wireless / bluetooth smart card readers in the market like:
[ACR1255U-J1](https://www.acs.com.hk/en/products/403/acr1255u-j1-acs-secure-bluetooth%C2%AE-nfc-reader/)
[Feitian bR500](https://www.ftsafe.com/store/product/bluetooth-card-reader/)
that claim to be PC/SC and CCID-compliant.

Has any non-usb smart card reader been tested with the CCID driver?
If not, how would you suppose they achieve this functionality? I guess using something like serial over bluetooth?
Lastly if they do operate with serial over bluetooth do you believe any of them would work with ccid_serial access enabled with `--enable-twinserial`?

**Comment by LudovicRousseau** [comment]
The CCID protocol is for USB only.

For a Bluetooth reader you have to provide your own PC/SC driver.
