### ISSUE TITLE
PCSC-LITE error

### ISSUE THREAD

**Issue by jason-young-ctct** [LudovicRousseau/CCID#127]
when running `sudo ./configure` on my Mac (Sonoma 14.2.1) I am getting the following error:
`configure: error: install pcsc-lite 1.8.3 or later, or use ./configure PCSC_CFLAGS=...`

I have pcsc-lite version 2.0.1 installed via homebrew.  I am not sure what needs to be done here.

**Comment by jason-young-ctct** [comment]
My mistake... I didn't see the instructions in the MacOSX folder.  It worked when using the correct instructions for my machine.

**Comment by LudovicRousseau** [comment]
https://ccid.apdu.fr/#MacOSX
