### ISSUE TITLE
MacOS Yosemite Problem

### ISSUE THREAD

**Issue by gerdogdu** [LudovicRousseau/CCID#14]
Hi 
I have installed the MILKO SmartCard Reader via the attached driver install script provider provided but smart card is not working. Mac OSX is Yosemite 10.10.4

When I opened the System Report it shows that 

MILKO v.2.4
Current Required (mA):	Unknown (Device has not been configured)**

What can be the problem?

Best
Gurkan
[Setup.txt](https://github.com/LudovicRousseau/CCID/files/176260/Setup.txt)

**Comment by LudovicRousseau** [comment]
You should report the problem to the provider of the script.

Or you can follow https://pcsclite.alioth.debian.org/ccid.html#CCID_compliant

**Comment by gerdogdu** [comment]
I downloaded source code but it gives the following error when configure:

configure: error: install pcsc-lite 1.8.3 or later, or use ./configure PCSC_CFLAGS=...

**Comment by LudovicRousseau** [comment]
For Mac OS X use ``./MacOSX/configure``
see https://pcsclite.alioth.debian.org/ccid.html#MacOSX

**Comment by gerdogdu** [comment]
Thanks but now I get the following error:
configure: error: libusb.h not found, install libusb or use ./configure LIBUSB_CFLAGS=...
+ rm -f src/Info.plist

**Comment by gerdogdu** [comment]
I run parse, it gives the following output

Parsing USB bus/device: 2A17:0001 (bus 20, device 26)
 idVendor:  0x2A17  iManufacturer: udea
 idProduct: 0x0001  iProduct: MILKO V2.4
  Can't get config descriptor: -5

**Comment by gerdogdu** [comment]
Do you have any comment on this?

**Comment by LudovicRousseau** [comment]
My comment is that your device is not a valid CCID device.
You should use a supported reader https://pcsclite.alioth.debian.org/ccid/supported.html

**Comment by gerdogdu** [comment]
But in release notes, it says support the Milko 
1.4.17 - 11 June 2014, Ludovic Rousseau
    - Add support of
      . udea MILKO V1.

**Comment by LudovicRousseau** [comment]
Your device is "iProduct: MILKO V2.4".
The one from my list is "iProduct: MILKO V1." https://pcsclite.alioth.debian.org/ccid/readers/udea_MILKO_V1.txt

It looks like udea (the manufacturer) changed the firmware. I don't know if your version if older or newer than the one I have in the list.

**Comment by gerdogdu** [comment]
How can I inspect logs ? Is there any log file to look further diagnose

**Comment by gerdogdu** [comment]
I noticed that there also exists /usr/libexec/SmartCardServices/drivers/ifd-acsccid.bundle/Contents/Info.plist but in this file, no milko found. Can it be a problem?
