### ISSUE TITLE
MacOSX installation not working on macOS Sonoma 14.5

### ISSUE THREAD

**Issue by danielmorozoff** [LudovicRousseau/CCID#141]
# Attempted Commands
```
 ./MacOSX/configure
```
yields `error: ./MacOSX/configure: line 130: ./configure: No such file or directory`

Code in `./configure` @ line 130

```
set -x
./configure \
	CFLAGS="$CFLAGS" \
	PCSC_CFLAGS="$PCSC_CFLAGS" \
	PCSC_LIBS="$PCSC_LIBS" \
	LIBUSB_CFLAGS="$LIBUSB_CFLAGS" \
	LIBUSB_LIBS="$LIBUSB_LIBS" \
	LDFLAGS="$LDFLAGS" \
	--enable-usbdropdir="$DROPDIR" \
	$CONFIGURE_ARGS \
	"$@"
```

Seems  `./configure`  is the culprit.

**Comment by LudovicRousseau** [comment]
libccid uses meson now. See https://blog.apdu.fr/posts/2024/06/libccid-now-uses-meson-build-tool/
`configure` is no more generated and distributed.

See also https://ccid.apdu.fr/#MacOSX

**Comment by LudovicRousseau** [comment]
You can also regenerate the `configure` script yourself using the `./bootstrap`  script.

**Comment by LudovicRousseau** [comment]
No feedback.
Closing
