### ISSUE TITLE
Card init fails

### ISSUE THREAD

**Issue by danielkucera** [LudovicRousseau/CCID#142]
this is the error when I run pcscd as system service:
```
jún 17 09:49:26 silverhorse pcscd[1353810]: 01403464 commands.c:1571:CCID_Receive Procedure byte conflict
jún 17 09:49:26 silverhorse pcscd[1353810]: 00000023 ifdwrapper.c:543:IFDTransmit() Card not transacted: 612
jún 17 09:49:26 silverhorse pcscd[1353810]: 00000004 winscard.c:1618:SCardTransmit() Card not transacted: 0x80100016
```
debug log is attached
[log.txt](https://github.com/user-attachments/files/15872281/log.txt)

the card works normally with `Gemalto PC Twin Reader (74558F51) 00 00` but doesn't work with `Alcor Micro AU9540 00 00`

**Comment by danielkucera** [comment]
The chip markings are AU9580

![IMG20240617102838](https://github.com/LudovicRousseau/CCID/assets/1734256/d95daf63-d7ed-4ee4-a042-9c8b6c927694)
![IMG20240617102823](https://github.com/LudovicRousseau/CCID/assets/1734256/9bd2c7eb-c0ec-44fb-9283-399b4bff6217)

**Comment by LudovicRousseau** [comment]
Install version CCID 1.5.2 or more and try again.
See https://blog.apdu.fr/posts/2023/01/new-version-of-libccid-152/

**Comment by danielkucera** [comment]
Thank you very much, that worked!
