### ISSUE TITLE
Any plan support CCID driver for Windows 10 IoT Core 

### ISSUE THREAD

**Issue by FeitianSmartcardReader** [LudovicRousseau/CCID#25]
Hi Ludovic

Did check Windows was publish their Windows 10 IoT based on Raspberry Pi 2&3, it doesn't have CCID driver default. 

Any plan support on this?

more information of Windows IoT: 
https://developer.microsoft.com/en-us/windows/iot
https://developer.microsoft.com/en-us/windows/iot/Explore/IoTCore

**Comment by LudovicRousseau** [comment]
No plan.
I do not use Windows.
