### ISSUE TITLE
New reader: ACR1255U-J1 ® Secure Bluetooth NFC Reader

### ISSUE THREAD

**Issue by frankmorgner** [LudovicRousseau/CCID#31]
[output.txt](https://github.com/LudovicRousseau/CCID/files/850366/output.txt)

Successfully tested the reader's USB interface with libccid-1.4.26 and pcsc-lite-1.8.13.

The [manufacturer's page](http://www.acs.com.hk/en/products/403/acr1255u-j1-secure-bluetooth%C2%AE-nfc-reader/) also includes a proprietary linux driver (which I didn't try).

**Comment by LudovicRousseau** [comment]
ACS provides a forked version https://github.com/acshk/acsccid of my CCID driver.
I guess you used the reader connected using USB only, not Bluetooth?

**Comment by frankmorgner** [comment]
Yes, USB only

**Comment by LudovicRousseau** [comment]
Add in the "Should work but untested by me" list
https://pcsclite.alioth.debian.org/ccid/shouldwork.html#0x072F0x223F
