### ISSUE TITLE
webusb support

### ISSUE THREAD

**Issue by yong86** [LudovicRousseau/CCID#33]
Hello,
Is there a way to use CCID with webusb or we need to implement it in javascript library?
Any plan for that?

**Comment by LudovicRousseau** [comment]
My CCID driver is C code and uses libusb.
I don't know how you can use it with webusb.

If you port my CCID driver in Javascript + webusb please tell me.

**Comment by yong86** [comment]
of course,I will let you know when I do succeed.

**Comment by sam-axiadids** [comment]
Would this approach work or would it still conflict with OS level pc/sc / Smart Card services?
