### ISSUE TITLE
No smart card inserted. [SCM Microsystems Inc. SCR 3310]

### ISSUE THREAD

**Issue by fredericosar** [LudovicRousseau/CCID#35]
Hello,

First, my apologies if this is the incorrect place for this question.

I am using a SCM Microsystems Inc. SCR 3310 and trying to read an AT88SC0404C.

When I run pcsctest I get the following results:

Enter the reader number          : 1
Waiting for card insertion         
                                                   : Command successful.
Testing SCardConnect             : No smart card inserted.

Any suggestion of what could be happening?

Thank you

**Comment by LudovicRousseau** [comment]
You should use the Pcsclite-muscle mailing list for support questions https://lists.alioth.debian.org/mailman/listinfo/pcsclite-muscle

It looks like the AT88SC0404C is a *memory* card and not a *smart* card. I am not surprised you can't use it.

**Comment by P-Xavier** [comment]
Memory card support would need tools from the reader vendors
http://support.identiv.com/developer-tools-for-smart-card-readers/
