### ISSUE TITLE
Need some help with understanding CCID

### ISSUE THREAD

**Issue by trialsNow** [LudovicRousseau/CCID#39]
I need some help with understanding the CCID concepts with respect to mac OS. 
Is it possible to register a non-usb smart card reader driver in a mac osx? I want to write a ccid reader driver that can talk over bluetooth. As I see all the documentation, the libusbccid driver registers only usb connected readers.

Can you please guide me where to start?

**Comment by LudovicRousseau** [comment]
See "Serial readers" at https://pcsclite.alioth.debian.org/api/group__IFDHandler.html and ``/etc/reader.conf``.
