### ISSUE TITLE
Serial non-usb readers help

### ISSUE THREAD

**Issue by trialsNow** [LudovicRousseau/CCID#41]
I am building an IFD reader in Mac OSx to work over the serial host and port..not sure if this has been worked before... I have couple of confusions around that

What I did so far:
Leveraging the vpcd (virtual smart card reader driver). 
Pushed the shared object on to /usr/local/libexec/Smartcardservices/drivers/Serial
Added etc/reader.conf

The reader is not shown on pcsctest. 

Where should the driver (serial driver)be placed (osx Sierra) so that the pcscd can pick that up?
I can't copy the share object to /usr/libexec/Smart cardServices/drivers. 

Any serial card readers sample in mac osx?? ANY minor help would be greatly appreciated

**Comment by LudovicRousseau** [comment]
Use the MUSCLE mailing list for questions NOT related to the CCID driver.
https://lists.infradead.org/mailman/listinfo/pcsclite-muscle
