### ISSUE TITLE
Yubico Yubikey 4 OTP+U2F+CCID init failed

### ISSUE THREAD

**Issue by bigon** [LudovicRousseau/CCID#47]
Hello,

I just bought a yubiley, the key is detected by the ccid driver but it doesn't work

libccid: 1.4.29
Debian unstable

[yuby_pcscd.txt](https://github.com/LudovicRousseau/CCID/files/1963949/yuby_pcscd.txt)

**Comment by LudovicRousseau** [comment]
Why do you say it does not work?
From the log I can see the Yubikey 4 ATR https://smartcard-atr.appspot.com/parse?ATR=3BF81300008131FE15597562696B657934D4

Please see https://ludovicrousseau.blogspot.fr/2014/03/level-1-smart-card-support-on-gnulinux.html

**Comment by bigon** [comment]
mmmh, indeed I overlooked the ATR at the end of the log file and got confused by the multiple interfaces on the device

**Comment by LudovicRousseau** [comment]
If gnupg does not work then you should ask support from gnupg team.
I am closing this issue.
