### ISSUE TITLE
con't find my evbSEC1212

### ISSUE THREAD

**Issue by bjthemost** [LudovicRousseau/CCID#55]
why CCID  con't find SEC1210 chip, I saw MICROCHIP SEC1210.txt in  CCID/readers dir,
and VID:0x0424:1202 in lsusb....

![_20180914095346](https://user-images.githubusercontent.com/33249191/45554322-b2c27c80-b868-11e8-9e92-34608ad3de5a.png)
![_20180914095336](https://user-images.githubusercontent.com/33249191/45554323-b35b1300-b868-11e8-9834-20beaf623388.png)

**Comment by bjthemost** [comment]
sorry , it's work......
but ,can't find SC2, in my EVB_SEC1212 dev board....

**Comment by LudovicRousseau** [comment]
You need to use CCID driver 1.4.16 or later
https://ccid.apdu.fr/ccid/shouldwork.html#0x04240x1202

**Comment by bjthemost** [comment]
thank you very much  for you hardly work :)
