### ISSUE TITLE
Do debug smart card and card reader under yosemite

### ISSUE THREAD

**Issue by FeitianSmartcardReader** [LudovicRousseau/CCID#6]
Hi Loduvic

I found the multi-slots reader, when do debug follow:
http://ludovicrousseau.blogspot.fr/2015/02/debug-smart-card-application-on-yosemite.html
http://ludovicrousseau.blogspot.co.uk/2015/02/debug-smart-card-reader-driver-on.html

I found it only first slot can print APDU transfer log.
the second card slot no transfer log between reader and card, please help to check.

sh-3.2# sh debug.sh 
1
Please plug out reader in 5s
894
Process 894 syslog filter mask: Off
Process 894 syslog filter mask: Emergency - Debug
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Critical>: 00000430 ccid_usb.c:1159:ControlUSB() control failed (20/16): -9 LIBUSB_ERROR_PIPE
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Notice>: logging slot 'Feitian R502(1)'
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 00144242 ccid_usb.c:574:OpenUSBByName() Found interface 1 but expecting 0
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 00000357 ccid_usb.c:576:OpenUSBByName() Wrong interface for USB device 20/16. Checking next one.
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 00001074 ccid_usb.c:596:OpenUSBByName() Found Vendor/Product: 096E/060D (Feitian R502)
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 00000108 ccid_usb.c:598:OpenUSBByName() Using USB bus/device: 20/16
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Critical>: 00000400 ccid_usb.c:1159:ControlUSB() control failed (20/16): -9 LIBUSB_ERROR_PIPE
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 00000107 ccid_usb.c:1090:get_data_rates() IFD does not support GET_DATA_RATES request: -9
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 00002706 ifdhandler.c:375:IFDHGetCapabilities() tag: 0xFAD, Feitian R502 (lun: 1)
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 00000152 ifdhandler.c:375:IFDHGetCapabilities() tag: 0x7A007, Feitian R502 (lun: 1)
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 00000124 ifdhandler.c:375:IFDHGetCapabilities() tag: 0xFAE, Feitian R502 (lun: 1)
Jun  7 15:18:57 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 00000119 ifdhandler.c:463:IFDHGetCapabilities() Reader supports 2 slot(s)
Jun  7 15:19:04 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Notice>: card in
Jun  7 15:19:04 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 06467281 ifdhandler.c:1139:IFDHPowerICC() action: Reset, Feitian R502 (lun: 0)
Jun  7 15:19:04 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Notice>: ATR:3b 9f 11 81 11 3d 00 13 78 80 00 00 00 00 00 00 00 00 00 00 00 c8
Jun  7 15:19:06 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Notice>: card out
Jun  7 15:19:11 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 07003450 ifdhandler.c:1139:IFDHPowerICC() action: Reset, Feitian R502 (lun: 1)

Jun  7 15:19:16 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 05225832 ifdhandler.c:1139:IFDHPowerICC() action: PowerDown, Feitian R502 (lun: 1)
Jun  7 15:19:17 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 01119068 ifdhandler.c:1139:IFDHPowerICC() action: Reset, Feitian R502 (lun: 1)
Jun  7 15:19:19 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Info>: 01594682 ifdhandler.c:1139:IFDHPowerICC() action: Reset, Feitian R502 (lun: 1)
Jun  7 15:19:19 Bens-MacBook-Pro.local com.apple.ifdreader[894] <Error>: 00257682 commands.c:249:CmdPowerOn Card absent or mute

**Comment by LudovicRousseau** [comment]
I confirm I have the same behaviour.
I guess the logging flag is switch off just after the first reader (first slot) is found.

It is an Apple bug. I can't help. Use http://bugreport.apple.com/
