### ISSUE TITLE
HID OMNIKEY 5025 CL : Open Port 0x200000 Failed

### ISSUE THREAD

**Issue by koyackien** [LudovicRousseau/CCID#64]
hi goodday,
can anyone help me with this error I've installed the driver in ubuntu but when i used the systemctl status pcscd i got this error !

Feb 17 09:01:06 isuser-ThinkCentre-M70e systemd[1]: Started PC/SC Smart Card Daemon.
Feb 17 09:01:06 isuser-ThinkCentre-M70e pcscd[2194]: HID HID Global OMNIKEY RFID  IA32 v2.10.0.1
Feb 17 09:01:06 isuser-ThinkCentre-M70e pcscd[2194]: 00000000 readerfactory.c:1106:RFInitializeReader() Open Port 0x200000 Failed (usb:076b/5124:libudev:0:/dev/bus/usb/004/002)
Feb 17 09:01:06 isuser-ThinkCentre-M70e pcscd[2194]: 00000020 readerfactory.c:376:RFAddReader() OMNIKEY 5x25 CL (HT-1350-1207090-00014) init failed.
Feb 17 09:01:06 isuser-ThinkCentre-M70e pcscd[2194]: 00000118 hotplug_libudev.c:523:HPAddDevice() Failed adding USB device: OMNIKEY 5x25 CL

**Comment by Vatsal-Makani** [comment]
What was the solution to your problem. I am facing the same with Omnikey 5427 CK
