### ISSUE TITLE
CCID_Receive() Can't read all data 49xyzkbytes

### ISSUE THREAD

**Issue by vjardin** [LudovicRousseau/CCID#66]
Some PKCS11 smart cards return some trailing 00 so we get this error,
  `CCID_Receive() Can't read all data 49174kbytes`
that lead to a failure of this test:
https://github.com/LudovicRousseau/CCID/blob/745c4efe214c1d3024b9cc62d52a653548c79818/src/commands.c#L1573
`if (length-10 != dw2i(cmd, 1))`

In fact, we should tolerate that the length is valid as long as we have enough payload, so it could become:
`if (length-10 != dw2i(cmd, 1))`

Without this patch, the following reader could not support some PKCS11 smart cards:
- Gemalto (was Gemplus) GemPC Twin
- Alcor Micro Corp. AU9540
- Feitian R502

Once it gets applied, they work fine.

The same fix was validated on some ACR with their CCID:
  https://github.com/acshk/acsccid/commit/e23befb5a80bf55bd817eca0102912aec90138ed

**Comment by LudovicRousseau** [comment]
The discussion happens in the PR https://github.com/LudovicRousseau/CCID/pull/67
So closing this issue.
