### ISSUE TITLE
Following #75 on PCSC, need to read some USB parameters

### ISSUE THREAD

**Issue by stephan57160** [LudovicRousseau/CCID#68]
Enhancement : Need to get some USB parameters, from CCID devices:

bus_number,
device_address,
device_port,
idProduct,
idVendor.
The parameters above can be used for a better identification of the devices, plugged on the host.

**Comment by LudovicRousseau** [comment]
Fixed

**Comment by LudovicRousseau** [comment]
See https://github.com/LudovicRousseau/CCID/pull/69
