### ISSUE TITLE
Why I didn't find Definition of SC_ERROR_INVALID_DATA、CCID_PIN_INSERT_OLD, etc

### ISSUE THREAD

**Issue by a295656031** [LudovicRousseau/CCID#71]
In which file is the definition of error code and Macro definition in the project？
Look forward to your reply

**Comment by LudovicRousseau** [comment]
Why do you think these symbols should be defined in this project?

**Comment by a295656031** [comment]
If not in the project, where can I find these definitions，thank you

**Comment by LudovicRousseau** [comment]
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/errors.h#L78
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/ccid-types.h#L84

**Comment by a295656031** [comment]
thank you very much
