### ISSUE TITLE
Is that possible to debug under macOS Catalina

### ISSUE THREAD

**Issue by FeitianSmartcardReader** [LudovicRousseau/CCID#75]
Trying build driver and to do debug under macOS Catalina, with below commands only can see the APDU level, already setup the log level to 7, doesn't work, is there anyway to print dump CCID format data in log?

Thanks you very much,

> sudo defaults write /Library/Preferences/com.apple.security.smartcard Logging -bool yes
log stream --predicate 'process == "com.apple.ifdreader"' --debug

**Comment by FeitianSmartcardReader** [comment]
@LudovicRousseau do you have any suggestion to print USB log? thanks

**Comment by LudovicRousseau** [comment]
Yes, it is possible but not easy.
Contact me on my private email.
