### ISSUE TITLE
Select MF on Omnikey 5427 and 5022

### ISSUE THREAD

**Issue by stephan57160** [LudovicRousseau/CCID#76]
I'm trying to figure out why these 2 readers don't have the same behaviour, regarding Select MF.

On one precise card, with the 5427, I'm unable to perform a Select MF, while it's ok with the 5022 (scard: Transaction failed).
With another card, both work fine with...

For info, I'm using a 1 year old PCSD/CCID lib and ebfe/scard in a GO application.

Any hint ?

**Comment by LudovicRousseau** [comment]
Ask this kind of question on the pcsclite-muscle mailing list https://lists.infradead.org/mailman/listinfo/pcsclite-muscle

**Comment by stephan57160** [comment]
I'll do. Thx.

**Comment by LudovicRousseau** [comment]
https://ludovicrousseau.blogspot.com/2020/11/how-to-get-smart-card-support.html
