### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kokoye2007** [LudovicRousseau/CCID#87]
# bootstrap / autoreconf

configure.ac:45: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:141: error: possibly undefined macro: AC_DEFINE
autoreconf: /usr/bin/autoconf failed with exit status: 1

# configure 

checking for -fvisibility=hidden... yes
./configure: line 13464: syntax error near unexpected token `newline'
./configure: line 13464: `	AX_PTHREAD('

**Comment by LudovicRousseau** [comment]
as indicated in https://ccid.apdu.fr/#download
"You will need to install dependencies like autoconf-archive."
