### ISSUE TITLE
"Generic EMV Smartcard Reader" not supporting IC cards with "Unresponsive card"

### ISSUE THREAD

**Issue by jakedolan443** [LudovicRousseau/CCID#88]
I recently tested a batch of 10 SLE 4442 memory cards on a reader (Generic EMV Smartcard Reader), which is advertised to support IC cards. I read in a previous issue that SLE 4442 were not supported by some readers, but the manufacturer of the reader has stated the reader should support these.
Using `pcsc_scan`:

```
 Reader 0: Generic EMV Smartcard Reader 00 00
  Event number: 0
  Card state: Card inserted, Unresponsive card
```

The [manufacturer](https://www.aliexpress.com/item/1005002708480163.html) states the reader is capable of memory cards. Forgive me if I am mistaken, but does the hardware and driver support this ?

**Comment by LudovicRousseau** [comment]
I have no idea. I would say NO.
See also https://ludovicrousseau.blogspot.com/2020/11/how-to-get-smart-card-support.html
