### ISSUE TITLE
SCL011 card reader not recognized

### ISSUE THREAD

**Issue by Konfekt** [LudovicRousseau/CCID#89]
As proposed at the [Opensuse bug report](https://bugzilla.opensuse.org/show_bug.cgi?id=1189308), this issue could be related to the ccid driver itself and therefore is posted here :

The SCL011 card reader (certified by the German government for the ID card according to http://www.personalausweis-kartenlesegeraete.de/basis-kartenleser/)  is not recognized after installing the driver package 

  pcsc-ccid

together with the packages libchipcard pcsc-lite.

Instead, what worked was:

First installing these packages libchipcard pcsc-lite and the package

 pcsc-lite-devel

Then downloading and uncompressing the Linux driver version 2.09 from 

  https://support.identiv.com/scl010-scl011/ 

to a folder $f and editing the file $f/proprietary/SCLGENERIC.bundle/Contents/Info.plist according to the instructions from https://forum.ubuntuusers.de/topic/problem-mit-treiber-kartenleser-scl/. 
That is, adding to the lists

      <key>ifdVendorId</key>
      <key>ifdProductId</key>
      <key>ifdFriendlyName</key>

the entries as shown by the command `lsusb` 

      <string>04e6</string>
      <string>5292</string>
      <string>SCM Microsystems, Inc. SCL011 RFID reader</string>

Then running `sudo $f/install.sh` and `sudo systemctl enable --now pcscd`.
(Maybe installing pcsc-lite-devel and running pcscd were dispensable.)

Thus, for this card reader to be recognized after installing the pcsc-ccid package, the above entries should be added to its file Info.plist.

**Comment by Konfekt** [comment]
Alas even the Identiv driver does not work out of the box. Any idea where this work-around could be documented or the corrected version uploaded? Perhaps https://ccid.apdu.fr/ccid/disabled.html#0x04E60x5292 could point it out?

**Comment by LudovicRousseau** [comment]
If I understand correctly the proprietary Identiv driver works after some changes. No?

I do not plan to document how to use proprietary drivers. Report the problem to Identiv and/or use a different reader model/manufacturer.
