### ISSUE TITLE
Not getting token serial number from token

### ISSUE THREAD

**Issue by kalyank23** [LudovicRousseau/CCID#93]
Please check the below input and output to the CCID

DEBUG [ykman.driver_ccid.send_apdu:224] SEND: 001d000000
DEBUG [ykman.driver_ccid.send_apdu:226] RECV: 2b0102023f0302001402040092634e04010105030501020602000007010f0801000d02023b0e0200000a01009000

and suggest why I am not able to read the serial number from token?

**Comment by LudovicRousseau** [comment]
https://ludovicrousseau.blogspot.com/2020/11/how-to-get-smart-card-support.html
