### ISSUE TITLE
Mixup of readers / add some "sanity check" for readers.txt?

### ISSUE THREAD

**Issue by martinpaljak** [LudovicRousseau/CCID#94]
I have a Feitian R502 reader that suddenly became Avtors. This might explain:

https://github.com/LudovicRousseau/CCID/blob/b2927edae089987a37c6fbdd6291c316c02c4500/readers/Avtor_SC_Reader_KP382.txt#L1-L4

https://github.com/LudovicRousseau/CCID/blob/b2927edae089987a37c6fbdd6291c316c02c4500/readers/Feitian_R502-CL.txt#L1-L4

I don't know if this is some kind of "OEM" re-branding, but at least mine is definitely Feitian-branded, Feitian-sourced. I don't approve such "OEM-rebrandings" by the manufacturer (can this be "fixed" by re-flasing?), but CCID driver could have some kind of sanity checks for duplicate identifiers.

This is how pcsc-lite sees it on Debian bullseye: "Avtor SC Reader KP382 [R502 Contactless Reader] (D861F9281400061A) 01 00"

**Comment by LudovicRousseau** [comment]
Hello Martin,
"many" readers are in fact rebranded.
I fixed the problem in https://github.com/LudovicRousseau/CCID/commit/07aefeb8fd2f40eb5e8c7d9fd737c0a917a22721

You can see all the duplicates in the... "duplicates" section https://github.com/LudovicRousseau/CCID/blob/master/readers/supported_readers.txt#L1010

**Comment by martinpaljak** [comment]
Thanks! Of course did not "see" the dups section... Interesting sidenote: this has also sneaked into usb.ids:
`Bus 001 Device 009: ID 096e:0608 Feitian Technologies, Inc. SC Reader KP382`
