### ISSUE TITLE
Install drivers on Windows

### ISSUE THREAD

**Issue by VictorMulet** [LudovicRousseau/CCID#98]
Is it possible to have an installer for Windows OS please ?
I'm working with an acs card reader and I've got this issue (Failed to transmit with protocol T1.) while trying to use the code PCSCReader from your pyscard library.
Thanks for your help, have a nice day

**Comment by LudovicRousseau** [comment]
This CCID driver is for Unix only.
I suggest you to erase Windows and install a GNU/Linux system instead.
